In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"D:\Data Science\udemy\Notebooks\08-Linear-Regression-Models\Advertising.csv")

In [4]:
X =df.drop('sales', axis = 1)

In [5]:
y = df['sales']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
poly_conv = PolynomialFeatures(degree=3, include_bias = False)

In [11]:
poly_feature = poly_conv.fit_transform(X)

In [12]:
poly_feature.shape

(200, 19)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(poly_feature, y, test_size=0.3, random_state = 101)

In [15]:
X_train.shape

(140, 19)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
scaler.fit(X_train)

StandardScaler()

In [19]:
X_train = scaler.transform(X_train)

In [20]:
X_test = scaler.transform(X_test)

In [21]:
X_train

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [22]:
  #sklearn lambda as alpha

In [24]:
from sklearn.linear_model import Ridge

In [25]:
ridge_model = Ridge(alpha=10)

In [26]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [27]:
y_pred = ridge_model.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [30]:
MAE = mean_absolute_error(y_test, y_pred)

In [31]:
MSE = mean_squared_error(y_test, y_pred)

In [32]:
RSME = MSE ** 0.5

In [33]:
print(f"MAE: {MAE}, MSE: {MSE}, RSME: {RSME}")

MAE: 0.5774404204714167, MSE: 0.8003783071528353, RSME: 0.894638646131965


In [53]:
from sklearn.linear_model import RidgeCV

In [59]:
ridge_cv_model = RidgeCV(
    alphas=(0.1, 1.0, 10),
    scoring='neg_mean_absolute_error'
)

In [60]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=(0.1, 1.0, 10), scoring='neg_mean_absolute_error')

In [61]:
ridge_cv_model.alpha_

0.1

In [62]:
# from sklearn.metrics import SCORERS

In [63]:
# SCORERS.keys()

In [64]:
y_pred_rcv = ridge_cv_model.predict(X_test)

In [68]:
MAE = mean_absolute_error(y_test, y_pred_rcv)

In [69]:
RMSE = mean_squared_error(y_test, y_pred_rcv) ** 0.5

In [70]:
MAE, RMSE

(0.4273774884351013, 0.6180719926948981)

In [72]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [74]:
ridge_cv_model.best_score_

-0.3749223340292953

In [76]:
 from sklearn.linear_model import LassoCV

In [99]:
lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)

In [100]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1)

In [101]:
lasso_cv_model.alpha_

0.4943070909225832

In [102]:
y_pred = lasso_cv_model.predict(X_test)

In [103]:
MAE = mean_absolute_error(y_test, y_pred)

In [104]:
RSME = mean_squared_error(y_test, y_pred)

In [105]:
MAE

0.6541723161252867

In [106]:
RSME

1.2787088713079886

In [107]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [108]:
from sklearn.linear_model import ElasticNetCV

In [109]:
elastic_model_cv = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], eps=0.001, n_alphas=100, max_iter=100000)

In [111]:
elastic_model_cv.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [113]:
elastic_model_cv.l1_ratio_

1.0

In [115]:
elastic_model_cv.alpha_

0.004943070909225833

In [116]:
y_pred = elastic_model_cv.predict(X_test)

In [118]:
MAE = mean_absolute_error(y_test, y_pred)

In [119]:
MAE

0.4335034618590078